export default {
    STORAGED_NOTES: 'STORAGE_NOTES',
    CURRENT_FILTER: 'CURRENT_FILTER',
    SELECTED_NOTE: 'SELECT_NOTE',
    RENDERED_NOTES_QTY: 'RENDERED_NOTES_QTY',
    SELECTED_NOTE_INDEX: 'SELECTED_NOTE_INDEX',
    STORAGED_ACTIONS: 'STORAGED_ACTIONS'
}